//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sibervatanprojemweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogsayfam
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string ozet { get; set; }
        public string etiket { get; set; }
        public string icerik { get; set; }
    }
}
